// Copyright (c) 2026 Rawabi Alharbi. SPDX-License-Identifier: MIT.

// Command mihakk is the Mihakk fuzzing engine CLI.
//
// Phase 1 ships the safety layer and the scope-check command. The run,
// reproduce and serve commands are added in later phases.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"time"

	"mihakk/internal/safety"
)

// Version identifies the engine build. It is part of every reproduction
// recipe: a case generated by one engine version is not assumed to regenerate
// identically on another.
const Version = "0.5.0-phase5"

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	switch os.Args[1] {
	case "version":
		fmt.Printf("mihakk %s\n", Version)
	case "scope-check":
		os.Exit(scopeCheck(os.Args[2:]))
	case "plan":
		os.Exit(planCmd(os.Args[2:]))
	case "run":
		os.Exit(runCmd(os.Args[2:]))
	case "reproduce":
		os.Exit(reproduceCmd(os.Args[2:]))
	case "serve":
		os.Exit(serveCmd(os.Args[2:]))
	case "help", "-h", "--help":
		usage()
	default:
		fmt.Fprintf(os.Stderr, "mihakk: unknown command %q\n\n", os.Args[1])
		usage()
		os.Exit(2)
	}
}

func usage() {
	fmt.Fprint(os.Stderr, `mihakk - defensive fuzzing engine

Usage:
  mihakk version
  mihakk scope-check -config <file> [-check-url <url>] [-method <method>]
  mihakk plan -corpus <file> -seed <seed> [-show <index>] [-dump]
  mihakk run -config <file> (-corpus <file> | -openapi <file>) [-seed <hex>]
  mihakk reproduce <case-id> -config <file> -corpus <file> [-data <dir>]
  mihakk serve [-addr <host:port>] [-data <dir>]    (MIHAKK_CONTROL_TOKEN required)
  mihakk serve -socket <path> [-health-addr <loopback:port>] [-data <dir>]

Commands:
  version       Print the engine version.
  scope-check   Validate a session config (scope, limits, authorisation)
                without sending a single request, and optionally test whether
                one URL would be allowed.
  plan          Inspect the deterministic mutation plan for a corpus, without
                sending anything. The same corpus, seed, settings and engine
                version always produce the same cases.
  run           Fuzz an authorised target: measure a baseline, execute the
                plan, and save every request that raised an indicator.
  reproduce     Re-send one saved case after re-validating authorisation,
                scope and limits, and report whether the same indicator
                appeared again.

  serve         Run the control API for the orchestrator. Listens on loopback
                by default and requires MIHAKK_CONTROL_TOKEN; every endpoint
                but /healthz needs that token. With -socket it listens on a
                Unix socket and on no network at all; -health-addr then adds
                a liveness endpoint that may only bind to loopback.

Results are indicators that need verification, never confirmed
vulnerabilities.
`)
}

func scopeCheck(args []string) int {
	fs := flag.NewFlagSet("scope-check", flag.ContinueOnError)
	configPath := fs.String("config", "", "path to the session config JSON (required)")
	checkURL := fs.String("check-url", "", "optional URL to test against the allowlist")
	method := fs.String("method", "GET", "method to use with -check-url")
	asJSON := fs.Bool("json", false, "emit machine-readable output")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *configPath == "" {
		fmt.Fprintln(os.Stderr, "mihakk: -config is required")
		return 2
	}

	cfg, err := safety.LoadSessionConfig(*configPath, time.Now())
	if err != nil {
		fmt.Fprintf(os.Stderr, "mihakk: config refused: %v\n", err)
		return 1
	}

	result := map[string]any{
		"config_version": cfg.ConfigVersion,
		"scope_digest":   cfg.Scope.Digest(),
		"config_digest":  cfg.Digest(),
		"engine_version": Version,
		"operator":       cfg.Authorization.Operator,
		"targets":        len(cfg.Scope.Targets),
		"limits":         cfg.Limits,
		"authorization":  "valid",
	}

	if *checkURL != "" {
		allowed, reason := checkOne(cfg, *method, *checkURL)
		result["check_url"] = *checkURL
		result["check_method"] = *method
		result["check_allowed"] = allowed
		result["check_reason"] = reason
	}

	if *asJSON {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		if err := enc.Encode(result); err != nil {
			fmt.Fprintf(os.Stderr, "mihakk: %v\n", err)
			return 1
		}
		return 0
	}

	fmt.Printf("config accepted\n")
	fmt.Printf("  engine version : %s\n", Version)
	fmt.Printf("  operator       : %s\n", cfg.Authorization.Operator)
	fmt.Printf("  targets        : %d\n", len(cfg.Scope.Targets))
	fmt.Printf("  scope digest   : %s\n", cfg.Scope.Digest())
	fmt.Printf("  config digest  : %s\n", cfg.Digest())
	fmt.Printf("  limits         : %.2f req/s, max %d requests, %d concurrent, %s session, %s timeout, %d bytes\n",
		cfg.Limits.RequestsPerSecond, cfg.Limits.MaxTotalRequests, cfg.Limits.MaxConcurrency,
		cfg.Limits.MaxSessionDuration.Duration(), cfg.Limits.RequestTimeout.Duration(),
		cfg.Limits.MaxResponseBytes)

	if *checkURL != "" {
		allowed, reason := checkOne(cfg, *method, *checkURL)
		if allowed {
			fmt.Printf("\n%s %s -> ALLOWED\n", *method, *checkURL)
		} else {
			fmt.Printf("\n%s %s -> REFUSED (%s)\n", *method, *checkURL, reason)
			return 1
		}
	}
	return 0
}

func checkOne(cfg *safety.SessionConfig, method, raw string) (bool, string) {
	u, err := parseURL(raw)
	if err != nil {
		return false, err.Error()
	}
	if _, err := cfg.Scope.Check(method, u); err != nil {
		return false, err.Error()
	}
	return true, "in scope"
}
