#!/usr/bin/env python3
"""Documented, local-testbed-only walkthrough. Never accepts an arbitrary target.

The acknowledgement generated by ``prepare`` names the bundled testbed only;
it must not be copied into an operator's real application configuration.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import pathlib
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import secrets_file  # noqa: E402
from local_api_transport import (FUTURE_ACK, clock_diagnostic,
                                 diagnostic_for_refusal, open_loopback)

SEED = "6d6968616b6b2d70686173652d352d35"
NOTE = "Results are indicators that need verification, not confirmed vulnerabilities."
STATEMENT = "I am authorised to test the targets listed in this scope."
LIMITS = {"requests_per_second": 20, "burst": 5, "max_total_requests": 400,
          "max_concurrency": 2, "max_session_duration": "3m",
          "request_timeout": "10s", "max_response_bytes": 1048576}


class DemoError(Exception):
    pass


def run(args: list[str], *, env: dict | None = None) -> str:
    result = subprocess.run(args, env=env, text=True, capture_output=True, timeout=45)
    if result.returncode:
        # Docker can echo interpolated environment on failure. Do not print it.
        raise DemoError(f"{args[0]} {args[1] if len(args) > 1 else ''} failed "
                        f"(exit {result.returncode})")
    return result.stdout


def compose_file() -> pathlib.Path:
    return pathlib.Path(os.environ.get("MIHAKK_COMPOSE_FILE") or
                        ROOT / "deploy/docker-compose.yml").resolve()


def port() -> int:
    value = int(os.environ.get("MIHAKK_PORT", "8100"))
    if not 1024 <= value <= 65535:
        raise DemoError("MIHAKK_PORT is outside the allowed range")
    return value


def secrets() -> dict:
    path = os.environ.get("MIHAKK_SECRETS_FILE") or str(
        pathlib.Path(os.environ.get("XDG_CONFIG_HOME") or pathlib.Path.home() / ".config") /
        "mihakk/secrets.env")
    return secrets_file.read(path)


def require_outside_repo(path: pathlib.Path) -> None:
    if path.resolve().is_relative_to(ROOT):
        raise DemoError("demo configuration and reports must stay outside the repository")


def request(path: str, *, body: dict | None = None, response_format: str = "json"):
    credential = secrets()["MIHAKK_DASHBOARD_TOKEN"]
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(
        f"http://127.0.0.1:{port()}{path}", data=data,
        headers={"Authorization": f"Bearer {credential}",
                 "Content-Type": "application/json"},
        method="POST" if body is not None else "GET")
    try:
        with open_loopback(req, timeout=20) as reply:
            if reply.status not in (200, 202):
                raise DemoError(f"API returned HTTP {reply.status}")
            raw = reply.read()
    except urllib.error.HTTPError as exc:
        if exc.code == 403:
            diagnostic = diagnostic_for_refusal(exc.read(8192), data or b"")
            if diagnostic is not None:
                print(diagnostic, file=sys.stderr)
        raise DemoError(f"API returned HTTP {exc.code}; response omitted") from None
    except urllib.error.URLError as exc:
        raise DemoError("the local orchestrator could not be reached") from exc
    return json.loads(raw) if response_format == "json" else raw


def testbed_address() -> str:
    # Read the committed (or test-namespaced) stack, then inspect only its own
    # testbed service. No caller-supplied host, URL, or network is accepted.
    env = {**os.environ, "MIHAKK_CONTROL_TOKEN": "placeholder-not-used",
           "MIHAKK_DASHBOARD_TOKEN": "placeholder-not-used"}
    compose = str(compose_file())
    config = json.loads(run(["docker", "compose", "-f", compose, "config",
                             "--no-interpolate", "--format", "json"], env=env))
    project = config.get("name")
    if not isinstance(project, str) or not re.fullmatch(r"[a-z0-9][a-z0-9_-]{2,62}", project):
        raise DemoError("the stack project name is missing or invalid")
    ids = run(["docker", "ps", "-q", "--filter", f"label=com.docker.compose.project={project}",
               "--filter", "label=com.docker.compose.service=testbed"]).split()
    if len(ids) != 1:
        raise DemoError("exactly one running local testbed container is required")
    detail = json.loads(run(["docker", "inspect", ids[0]]))[0]
    networks = detail["NetworkSettings"]["Networks"]
    if len(networks) != 1:
        raise DemoError("the local testbed must be on exactly one isolated network")
    network_name, attachment = next(iter(networks.items()))
    network = json.loads(run(["docker", "network", "inspect", network_name]))[0]
    ports = detail["NetworkSettings"].get("Ports") or {}
    if network.get("Internal") is not True or any(ports.values()):
        raise DemoError("the local testbed is not isolated from the host")
    ip = attachment.get("IPAddress", "")
    if not re.fullmatch(r"\d{1,3}(?:\.\d{1,3}){3}", ip):
        raise DemoError("the local testbed's IPv4 address is unavailable")
    return ip


def prepare(path: pathlib.Path, acknowledged: bool) -> None:
    if not acknowledged:
        raise DemoError("explicit --ack-local-testbed is required; never use this for a real owner")
    require_outside_repo(path)
    if path.exists():
        raise DemoError("the demo configuration already exists; refusing to overwrite it")
    ip = testbed_address()
    config = {
        "config_version": "1",
        "scope": {"targets": [{"scheme": "http", "host": "testbed", "port": 8000,
                              "path_prefixes": ["/api"], "methods": ["GET", "POST"],
                              "allowed_addresses": [f"{ip}/32"]}], "max_redirects": 2},
        "limits": LIMITS,
        "authorization": {
            "operator": "local-testbed-demo-only",
            "statement": STATEMENT,
            "acked_at": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "scope_digest": "sha256:" + "0" * 64},
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    # The scope checker only reads this one file; no token is mounted.
    with os.fdopen(os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600), "w") as handle:
        json.dump(config, handle, indent=2)
        handle.write("\n")
    try:
        result = subprocess.run(["docker", "run", "--rm", "--network", "none",
                                 "--user", "0:0",
                                 "-v", f"{path.parent}:/work:ro", "mihakk-engine:dev",
                                 "scope-check", "-config", f"/work/{path.name}"],
                                text=True, capture_output=True, timeout=30)
        digest = re.search(r"the configured scope is (sha256:[0-9a-f]{64})",
                           result.stdout + result.stderr)
        if digest is None:
            if FUTURE_ACK in result.stderr.encode():
                print(clock_diagnostic(config["authorization"]["acked_at"]),
                      file=sys.stderr)
            safe_reason = re.sub(r"[0-9a-f]{32,}", "[hex]", result.stderr.strip())[:180]
            raise DemoError(f"scope-check did not return a digest for the local testbed "
                            f"(exit {result.returncode}; {safe_reason})")
        config["authorization"]["scope_digest"] = digest.group(1)
        path.write_text(json.dumps(config, indent=2) + "\n")
    except BaseException:
        path.unlink(missing_ok=True)
        raise
    print(f"Prepared local testbed scope and acknowledgement in {path}; no public target was used.")


def start(config_path: pathlib.Path, session: str, seed: str) -> None:
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", session):
        raise DemoError("invalid demo session id")
    if not re.fullmatch(r"[0-9a-f]{32,128}", seed):
        raise DemoError("seed must be 32–128 lowercase hexadecimal characters")
    config = json.loads(config_path.read_text())
    expected_scope = {"targets": [{"scheme": "http", "host": "testbed", "port": 8000,
                                   "path_prefixes": ["/api"], "methods": ["GET", "POST"],
                                   "allowed_addresses": [f"{testbed_address()}/32"]}],
                      "max_redirects": 2}
    auth = config.get("authorization") or {}
    if (config.get("config_version") != "1" or config.get("scope") != expected_scope
            or config.get("limits") != LIMITS
            or auth.get("operator") != "local-testbed-demo-only"
            or auth.get("statement") != STATEMENT):
        raise DemoError("only a current local testbed configuration is accepted")
    corpus = json.loads((ROOT / "testbed/corpus.json").read_text())
    answer = request(f"/v1/sessions/{session}/start", body={
        "session_id": session, "config": config, "corpus": corpus,
        "seed": seed, "max_cases": 120})
    if answer.get("status") != "running":
        raise DemoError("the demo session was not accepted")
    print(f"Started local testbed session {session} with the bundled corpus and seed {seed}.")


def follow(session: str) -> None:
    for _ in range(180):
        view = request(f"/v1/sessions/{session}")
        if view.get("status") != "running":
            print(f"Session {session}: {view.get('status')}; completeness={view.get('completeness', {}).get('complete')}.")
            if view.get("status") != "completed":
                raise DemoError("the local testbed session did not complete; inspect it before using reports")
            return
        time.sleep(1)
    raise DemoError("the local testbed session did not finish within three minutes")


def report(session: str, fmt: str, output: pathlib.Path) -> None:
    require_outside_repo(output)
    if output.exists():
        raise DemoError("the report output already exists; refusing to overwrite it")
    raw = request(f"/v1/sessions/{session}/report?format={fmt}", response_format="bytes")
    if fmt == "json":
        parsed = json.loads(raw)
        if parsed.get("note") != NOTE:
            raise DemoError("JSON report does not carry the required indicator warning")
    elif NOTE.encode() not in raw:
        raise DemoError("HTML report does not carry the required indicator warning")
    output.parent.mkdir(parents=True, exist_ok=True)
    with os.fdopen(os.open(output, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600), "wb") as handle:
        handle.write(raw)
    print(f"Saved {fmt.upper()} report to {output}. Results are indicators needing verification.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    subs = parser.add_subparsers(dest="action", required=True)
    prep = subs.add_parser("prepare")
    prep.add_argument("--ack-local-testbed", action="store_true")
    prep.add_argument("--output", required=True, type=pathlib.Path)
    begin = subs.add_parser("start")
    begin.add_argument("--config", required=True, type=pathlib.Path)
    begin.add_argument("--session", required=True)
    begin.add_argument("--seed", default=SEED)
    watch = subs.add_parser("follow")
    watch.add_argument("--session", required=True)
    fetch = subs.add_parser("report")
    fetch.add_argument("--session", required=True)
    fetch.add_argument("--format", choices=("json", "html"), required=True)
    fetch.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()
    try:
        if args.action == "prepare":
            prepare(args.output, args.ack_local_testbed)
        elif args.action == "start":
            start(args.config, args.session, args.seed)
        elif args.action == "follow":
            follow(args.session)
        else:
            report(args.session, args.format, args.output)
    except (DemoError, OSError, ValueError, KeyError, IndexError) as exc:
        print(f"local testbed demo: {exc}", file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
