// Package mutate turns a corpus of valid requests into a deterministic
// sequence of mutated ones.
//
// The reproducibility contract is that case number i is a *pure function* of
// (master seed, engine version, corpus digest, config digest, i). Nothing in
// generation reads shared mutable state, consults a clock, or depends on which
// worker runs it or in what order workers finish. Sorting results by case
// index therefore recovers the same sequence every time, on any machine, at
// any concurrency, in any process.
//
// This guarantees the *inputs* only. It says nothing about how the target
// responds: replaying the same request can produce a different status, a
// different latency, or no indicator at all.
package mutate

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"sort"
	"strings"

	"mihakk/internal/corpus"
)

// DerivationDomain namespaces the derivation hash. Changing it would change
// every generated mutation, so it is versioned and must not be edited
// casually.
const DerivationDomain = "mihakk/mutate/v1"

var (
	// ErrPlanEmpty means the corpus and config produced no mutable targets.
	ErrPlanEmpty = errors.New("mihakk: mutation plan is empty (no mutable targets in the corpus)")
	// ErrCaseOutOfRange means the requested case index does not exist.
	ErrCaseOutOfRange = errors.New("mihakk: case index out of range")
	// ErrDestinationChanged means a mutation tried to move the request. It is
	// an internal invariant failure, not something a user can cause.
	ErrDestinationChanged = errors.New("mihakk: mutation changed the request destination")
	// ErrSampleExceedsLimits means a sample is already larger than the
	// configured caps, so no case built from it could honour them.
	ErrSampleExceedsLimits = errors.New("mihakk: sample exceeds the configured size limits")
	// ErrCaseExceedsLimits means a generated case could not be brought inside
	// the size caps even after falling back to an empty value. Case returns
	// this instead of handing back an oversized request.
	ErrCaseExceedsLimits = errors.New("mihakk: generated case exceeds the configured size limits")
)

// Request is a generated request, ready to be handed to the safety layer.
type Request struct {
	Method  string              `json:"method"`
	URL     string              `json:"url"`
	Headers map[string][]string `json:"headers,omitempty"`
	Body    []byte              `json:"body,omitempty"`
}

// Case is one generated mutation.
type Case struct {
	Index      int        `json:"index"`
	SampleID   string     `json:"sample_id"`
	TargetKind TargetKind `json:"target_kind"`
	TargetName string     `json:"target_name"`
	Mutator    string     `json:"mutator"`
	Request    Request    `json:"request"`
}

// Canonical returns a deterministic byte form of the case, used to compare
// sequences generated by different runs or different processes.
func (c *Case) Canonical() []byte {
	b, err := json.Marshal(c)
	if err != nil {
		panic("mutate: canonical: " + err.Error())
	}
	return b
}

// sampleTargets caches the deterministic target list for one sample.
type sampleTargets struct {
	sample  *corpus.Sample
	targets []Target
}

// Plan enumerates the mutation space. It is immutable after construction and
// safe for concurrent use: Case never writes to it.
type Plan struct {
	cfg           Config
	engineVersion string
	seed          []byte

	corpusDigest string
	configDigest string
	derivation   [32]byte

	perSample []sampleTargets
	offsets   []int // offsets[i] is the first case index of sample i
	total     int
}

// NewPlan builds the plan. seed is the session's master seed.
func NewPlan(c *corpus.Corpus, cfg Config, engineVersion string, seed []byte) (*Plan, error) {
	if c == nil {
		return nil, fmt.Errorf("%w: corpus is required", ErrInvalidConfig)
	}
	if strings.TrimSpace(engineVersion) == "" {
		return nil, fmt.Errorf("%w: engine version is required", ErrInvalidConfig)
	}
	if len(seed) == 0 {
		return nil, fmt.Errorf("%w: seed is required", ErrInvalidConfig)
	}

	c.Normalize()
	if err := c.Validate(); err != nil {
		return nil, err
	}
	cfg.Normalize()
	if err := cfg.Validate(); err != nil {
		return nil, err
	}

	p := &Plan{
		cfg:           cfg,
		engineVersion: engineVersion,
		seed:          append([]byte(nil), seed...),
		corpusDigest:  c.Digest(),
		configDigest:  cfg.Digest(),
	}

	// The derivation binds every input that must change the output.
	h := sha256.New()
	writeField(h, DerivationDomain)
	writeField(h, engineVersion)
	writeField(h, string(seed))
	writeField(h, p.corpusDigest)
	writeField(h, p.configDigest)
	h.Sum(p.derivation[:0])
	copy(p.derivation[:], h.Sum(nil))

	for i := range c.Samples {
		s := &c.Samples[i]
		// The size caps bound the whole generated request, not just the part a
		// mutation touched: a case that fuzzes a query parameter still sends
		// the sample's body untouched. Rejecting an oversized sample here is
		// honest, where silently truncating operator-supplied data would
		// corrupt every case built from it.
		if err := checkSampleFitsLimits(s, &cfg); err != nil {
			return nil, err
		}
		targets, err := enumerateTargets(s, &cfg)
		if err != nil {
			return nil, err
		}
		if len(targets) == 0 {
			continue
		}
		p.offsets = append(p.offsets, p.total)
		p.perSample = append(p.perSample, sampleTargets{sample: s, targets: targets})
		p.total += len(targets) * cfg.MutationsPerTarget
	}
	if p.total == 0 {
		return nil, ErrPlanEmpty
	}
	return p, nil
}

// checkSampleFitsLimits rejects a sample that could never satisfy the caps.
func checkSampleFitsLimits(s *corpus.Sample, cfg *Config) error {
	body, err := s.DecodedBody()
	if err != nil {
		return err
	}
	if len(body) > cfg.MaxBodyBytes {
		return fmt.Errorf("%w: sample %q has a %d byte body but max_body_bytes is %d; "+
			"raise the limit or use a smaller sample", ErrSampleExceedsLimits, s.ID, len(body), cfg.MaxBodyBytes)
	}
	if len(s.URL) > cfg.MaxURLBytes {
		return fmt.Errorf("%w: sample %q has a %d byte url but max_url_bytes is %d",
			ErrSampleExceedsLimits, s.ID, len(s.URL), cfg.MaxURLBytes)
	}

	// A mutated query is rebuilt with url.Values.Encode, which percent-encodes
	// what the sample may have carried literally. That re-encoding can make
	// the URL longer than the sample's own text -- a 4-byte rune becomes 12
	// characters -- so the cap has to be checked against the encoded form too.
	// Emptying a value only shrinks this, so a sample that fits here also
	// fits after any fallback.
	if cfg.MutateQuery {
		u, err := s.ParsedURL()
		if err != nil {
			return err
		}
		encoded := *u
		encoded.RawQuery = u.Query().Encode()
		if n := len(encoded.String()); n > cfg.MaxURLBytes {
			return fmt.Errorf("%w: sample %q url is %d bytes once re-encoded (raw: %d) "+
				"but max_url_bytes is %d; percent-encoding expands it",
				ErrSampleExceedsLimits, s.ID, n, len(s.URL), cfg.MaxURLBytes)
		}
	}

	// The same applies to a body that is rebuilt rather than passed through.
	if cfg.MutateBody {
		switch s.BodyKind() {
		case corpus.BodyForm:
			values, err := url.ParseQuery(string(body))
			if err != nil {
				return fmt.Errorf("%w: sample %q form body does not parse: %v", ErrInvalidConfig, s.ID, err)
			}
			if n := len(values.Encode()); n > cfg.MaxBodyBytes {
				return fmt.Errorf("%w: sample %q form body is %d bytes once re-encoded (raw: %d) "+
					"but max_body_bytes is %d", ErrSampleExceedsLimits, s.ID, n, len(body), cfg.MaxBodyBytes)
			}
		case corpus.BodyJSON:
			doc, err := decodeJSON(body)
			if err != nil {
				return fmt.Errorf("%w: sample %q: %v", ErrInvalidConfig, s.ID, err)
			}
			encoded, err := json.Marshal(doc)
			if err != nil {
				return fmt.Errorf("%w: sample %q: %v", ErrInvalidConfig, s.ID, err)
			}
			// encoding/json escapes <, > and & as \u003c and friends, so a
			// re-encoded body can also outgrow the original text.
			if n := len(encoded); n > cfg.MaxBodyBytes {
				return fmt.Errorf("%w: sample %q json body is %d bytes once re-encoded (raw: %d) "+
					"but max_body_bytes is %d", ErrSampleExceedsLimits, s.ID, n, len(body), cfg.MaxBodyBytes)
			}
		}
	}
	// MaxValueBytes is deliberately not checked here. It caps a value that a
	// mutation *produces*; a sample's own headers are operator-supplied and
	// pass through untouched, and a normal Content-Type already runs to 33
	// bytes. Rejecting a corpus because the operator wanted short mutated
	// values would be surprising and wrong.
	return nil
}

// writeField hashes a length-prefixed field so that concatenating different
// field values cannot produce the same digest.
func writeField(h interface{ Write([]byte) (int, error) }, v string) {
	var n [8]byte
	binary.BigEndian.PutUint64(n[:], uint64(len(v)))
	_, _ = h.Write(n[:])
	_, _ = h.Write([]byte(v))
}

// Total is the number of cases in the plan.
func (p *Plan) Total() int { return p.total }

// Config returns the mutation settings this plan was built with. A saved case
// records these alongside its seed: rebuilding the plan with different
// settings changes how many cases it has, so the case index would point
// somewhere else, or nowhere at all.
func (p *Plan) Config() Config { return p.cfg }

// DerivationDigest fingerprints every input that determines the sequence.
// Two plans with the same derivation digest generate identical cases.
func (p *Plan) DerivationDigest() string {
	return "sha256:" + hex.EncodeToString(p.derivation[:])
}

// CorpusDigest and ConfigDigest are recorded with every saved case so a later
// reproduce can detect that its inputs drifted.
func (p *Plan) CorpusDigest() string  { return p.corpusDigest }
func (p *Plan) ConfigDigest() string  { return p.configDigest }
func (p *Plan) EngineVersion() string { return p.engineVersion }

// caseKey derives the per-case stream key. It is a pure function of the
// derivation and the index, which is what removes any dependence on worker
// scheduling: no shared RNG, no sequence position, no ordering.
func (p *Plan) caseKey(index int) [32]byte {
	h := sha256.New()
	_, _ = h.Write(p.derivation[:])
	writeField(h, "case")
	var n [8]byte
	binary.BigEndian.PutUint64(n[:], uint64(index))
	_, _ = h.Write(n[:])
	var key [32]byte
	copy(key[:], h.Sum(nil))
	return key
}

// targetKey derives a per-target value used to rotate mutator selection, so
// different fields exercise different mutators first.
func (p *Plan) targetKey(sampleID, targetName string) [32]byte {
	h := sha256.New()
	_, _ = h.Write(p.derivation[:])
	writeField(h, "target")
	writeField(h, sampleID)
	writeField(h, targetName)
	var key [32]byte
	copy(key[:], h.Sum(nil))
	return key
}

// locate maps a case index to its sample, target and repetition.
func (p *Plan) locate(index int) (st sampleTargets, target Target, rep int, err error) {
	if index < 0 || index >= p.total {
		return st, target, 0, fmt.Errorf("%w: %d (plan has %d cases)", ErrCaseOutOfRange, index, p.total)
	}
	// offsets is ascending; find the last entry that is <= index.
	i := sort.Search(len(p.offsets), func(i int) bool { return p.offsets[i] > index }) - 1
	st = p.perSample[i]
	local := index - p.offsets[i]
	targetIdx := local / p.cfg.MutationsPerTarget
	rep = local % p.cfg.MutationsPerTarget
	return st, st.targets[targetIdx], rep, nil
}

// Case generates case number index. It is pure: the same plan and index
// always produce the same bytes, whatever else is running.
func (p *Plan) Case(index int) (*Case, error) {
	st, target, rep, err := p.locate(index)
	if err != nil {
		return nil, err
	}
	sample := st.sample

	s := newStream(p.caseKey(index))
	rotate := newStream(p.targetKey(sample.ID, string(target.Kind)+":"+target.Name))

	out := &Case{
		Index:      index,
		SampleID:   sample.ID,
		TargetKind: target.Kind,
		TargetName: target.Name,
	}

	req, mutator, err := p.applyMutation(sample, target, rep, s, rotate)
	if err != nil {
		return nil, err
	}
	out.Mutator = mutator
	out.Request = req

	// Authoritative size check on the bytes that would actually be sent. Each
	// branch already caps its own output, but percent-encoding and JSON
	// escaping make those budgets estimates; this is the guarantee that Case
	// never hands back an over-limit request.
	if n := len(out.Request.URL); n > p.cfg.MaxURLBytes {
		return nil, fmt.Errorf("%w: case %d url is %d bytes (cap %d)",
			ErrCaseExceedsLimits, index, n, p.cfg.MaxURLBytes)
	}
	if n := len(out.Request.Body); n > p.cfg.MaxBodyBytes {
		return nil, fmt.Errorf("%w: case %d body is %d bytes (cap %d)",
			ErrCaseExceedsLimits, index, n, p.cfg.MaxBodyBytes)
	}

	// Invariant: a mutation may change what is sent, never where it is sent.
	// The safety layer re-checks scope before every request regardless; this
	// catches a generator bug at the source instead of burning budget on
	// requests the scope guard would refuse.
	if err := assertSameDestination(sample, &out.Request); err != nil {
		return nil, err
	}
	return out, nil
}

// applyMutation dispatches on target kind and returns the mutated request.
func (p *Plan) applyMutation(sample *corpus.Sample, target Target, rep int, s, rotate *stream) (Request, string, error) {
	u, err := sample.ParsedURL()
	if err != nil {
		return Request{}, "", err
	}
	body, err := sample.DecodedBody()
	if err != nil {
		return Request{}, "", err
	}

	req := Request{
		Method:  sample.Method,
		URL:     u.String(),
		Headers: cloneHeaders(sample.Headers),
		Body:    body,
	}

	switch target.Kind {
	case TargetQuery:
		m := pickStringMutator(rotate, rep)
		q := u.Query()
		values := q[target.Name]
		if target.ValueIndex >= len(values) {
			return Request{}, "", fmt.Errorf("mutate: query %q index %d no longer exists", target.Name, target.ValueIndex)
		}
		budget := p.valueBudget(len(u.String()) - len(values[target.ValueIndex]))
		values[target.ValueIndex] = m.apply(s, values[target.ValueIndex], budget)
		q[target.Name] = values
		mutated := *u
		mutated.RawQuery = q.Encode()
		if len(mutated.String()) > p.cfg.MaxURLBytes {
			// The byte budget is only an estimate: Encode percent-encodes the
			// value, and one 4-byte rune becomes 12 characters. Fall back to
			// an empty value.
			values[target.ValueIndex] = ""
			q[target.Name] = values
			mutated.RawQuery = q.Encode()
		}
		// Re-check the bytes that would actually be sent. The fallback shrinks
		// the URL, but it is the encoded length that has to satisfy the cap,
		// so it is verified rather than assumed.
		if n := len(mutated.String()); n > p.cfg.MaxURLBytes {
			return Request{}, "", fmt.Errorf("%w: query %q produced a %d byte url (cap %d) "+
				"even with an empty value", ErrCaseExceedsLimits, target.Name, n, p.cfg.MaxURLBytes)
		}
		req.URL = mutated.String()
		return req, m.name, nil

	case TargetHeader:
		m := pickStringMutator(rotate, rep)
		values := req.Headers[target.Name]
		if target.ValueIndex >= len(values) {
			return Request{}, "", fmt.Errorf("mutate: header %q index %d no longer exists", target.Name, target.ValueIndex)
		}
		values[target.ValueIndex] = sanitizeHeaderValue(m.apply(s, values[target.ValueIndex], p.cfg.MaxValueBytes))
		return req, m.name, nil

	case TargetForm:
		m := pickStringMutator(rotate, rep)
		values, err := url.ParseQuery(string(body))
		if err != nil {
			return Request{}, "", err
		}
		list := values[target.Name]
		if target.ValueIndex >= len(list) {
			return Request{}, "", fmt.Errorf("mutate: form field %q index %d no longer exists", target.Name, target.ValueIndex)
		}
		budget := p.valueBudget(len(body) - len(list[target.ValueIndex]))
		list[target.ValueIndex] = m.apply(s, list[target.ValueIndex], budget)
		values[target.Name] = list
		encoded := values.Encode()
		if len(encoded) > p.cfg.MaxBodyBytes {
			list[target.ValueIndex] = ""
			values[target.Name] = list
			encoded = values.Encode()
		}
		if n := len(encoded); n > p.cfg.MaxBodyBytes {
			return Request{}, "", fmt.Errorf("%w: form field %q produced a %d byte body (cap %d) "+
				"even with an empty value", ErrCaseExceedsLimits, target.Name, n, p.cfg.MaxBodyBytes)
		}
		req.Body = []byte(encoded)
		return req, m.name, nil

	case TargetJSON:
		m := pickJSONMutator(rotate, rep)
		doc, err := decodeJSON(body)
		if err != nil {
			return Request{}, "", err
		}
		original, ok := getAtPath(doc, target.steps)
		if !ok {
			return Request{}, "", fmt.Errorf("mutate: json path %s no longer exists", target.Name)
		}
		budget := p.valueBudget(len(body) - len(jsonText(original)))
		mutatedDoc, err := setAtPath(doc, target.steps, m.apply(s, original, budget))
		if err != nil {
			return Request{}, "", err
		}
		encoded, err := json.Marshal(mutatedDoc)
		if err != nil {
			return Request{}, "", fmt.Errorf("mutate: re-encoding mutated json: %w", err)
		}
		if len(encoded) > p.cfg.MaxBodyBytes {
			// Deterministic fallbacks, smallest last. Truncating the encoded
			// bytes would satisfy the cap while producing invalid JSON that no
			// longer represents the mutation, so it is not done.
			for _, fallback := range []any{"", nil} {
				fresh, err := decodeJSON(body)
				if err != nil {
					return Request{}, "", err
				}
				shrunk, err := setAtPath(fresh, target.steps, fallback)
				if err != nil {
					return Request{}, "", err
				}
				candidate, err := json.Marshal(shrunk)
				if err != nil {
					return Request{}, "", err
				}
				encoded = candidate
				if len(encoded) <= p.cfg.MaxBodyBytes {
					break
				}
			}
		}
		if n := len(encoded); n > p.cfg.MaxBodyBytes {
			return Request{}, "", fmt.Errorf("%w: json path %s produced a %d byte body (cap %d) "+
				"even after shrinking the node", ErrCaseExceedsLimits, target.Name, n, p.cfg.MaxBodyBytes)
		}
		req.Body = encoded
		return req, m.name, nil

	case TargetRawBody:
		m := pickRawMutator(rotate, rep)
		mutated := m.apply(s, body, p.cfg.MaxBodyBytes)
		if len(mutated) > p.cfg.MaxBodyBytes {
			mutated = mutated[:p.cfg.MaxBodyBytes]
		}
		req.Body = mutated
		return req, m.name, nil
	}
	return Request{}, "", fmt.Errorf("mutate: unknown target kind %q", target.Kind)
}

// valueBudget is how many bytes a single mutated value may occupy, given how
// much of the size cap the rest of the request already uses.
func (p *Plan) valueBudget(usedByRest int) int {
	remaining := p.cfg.MaxBodyBytes - usedByRest
	if remaining < 0 {
		remaining = 0
	}
	return minInt(p.cfg.MaxValueBytes, maxInt(0, remaining))
}

// pickStringMutator rotates through the mutator list starting at a per-target
// offset, so a field with few repetitions still sees varied mutators while the
// choice stays a pure function of the inputs.
func pickStringMutator(rotate *stream, rep int) stringMutator {
	offset := rotate.intn(len(stringMutators))
	return stringMutators[(offset+rep)%len(stringMutators)]
}

func pickJSONMutator(rotate *stream, rep int) jsonMutator {
	offset := rotate.intn(len(jsonMutators))
	return jsonMutators[(offset+rep)%len(jsonMutators)]
}

func pickRawMutator(rotate *stream, rep int) rawMutator {
	offset := rotate.intn(len(rawMutators))
	return rawMutators[(offset+rep)%len(rawMutators)]
}

func cloneHeaders(in map[string][]string) map[string][]string {
	if len(in) == 0 {
		return nil
	}
	out := make(map[string][]string, len(in))
	for k, v := range in {
		out[k] = append([]string(nil), v...)
	}
	return out
}

// sanitizeHeaderValue strips CR and LF. A newline in a header value would let
// a mutation forge additional headers, which is request smuggling rather than
// input fuzzing, and net/http would reject it anyway.
func sanitizeHeaderValue(v string) string {
	return strings.NewReplacer("\r", " ", "\n", " ", "\x00", " ").Replace(v)
}

// assertSameDestination enforces that a mutation changed only the payload.
func assertSameDestination(sample *corpus.Sample, req *Request) error {
	original, err := sample.ParsedURL()
	if err != nil {
		return err
	}
	mutated, err := url.Parse(req.URL)
	if err != nil {
		return fmt.Errorf("%w: generated url does not parse: %v", ErrDestinationChanged, err)
	}
	switch {
	case req.Method != sample.Method:
		return fmt.Errorf("%w: method %q became %q", ErrDestinationChanged, sample.Method, req.Method)
	case mutated.Scheme != original.Scheme:
		return fmt.Errorf("%w: scheme %q became %q", ErrDestinationChanged, original.Scheme, mutated.Scheme)
	case mutated.Host != original.Host:
		return fmt.Errorf("%w: host %q became %q", ErrDestinationChanged, original.Host, mutated.Host)
	case mutated.Path != original.Path:
		return fmt.Errorf("%w: path %q became %q", ErrDestinationChanged, original.Path, mutated.Path)
	case mutated.User != nil:
		return fmt.Errorf("%w: credentials appeared in the url", ErrDestinationChanged)
	}
	if hostHeader, ok := req.Headers["Host"]; ok && len(hostHeader) > 0 {
		if sampleHost, had := sample.Headers["Host"]; !had || len(sampleHost) == 0 || sampleHost[0] != hostHeader[0] {
			return fmt.Errorf("%w: Host header was altered", ErrDestinationChanged)
		}
	}
	return nil
}
